import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import Footer from "@/components/shared/Footer";

const spaceGrotesk = Space_Grotesk({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${spaceGrotesk.className} `}>
        <Navbar />
        <div className="h-12"></div>
        <div className="container max-w-4xl mx-auto px-4 lg:px-0">
          {children}
        </div>
        <div className="h-12"></div>
        <Footer />
      </body>
    </html>
  );
}
